// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class File {
    /**
     * Creates a new File instance.
     * @param {Partial<File>} [$$source = {}] - The source object to create the File.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("ProjectID" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["ProjectID"] = null;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new File instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {File}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new File(/** @type {Partial<File>} */($$parsedSource));
    }
}

export class Version {
    /**
     * Creates a new Version instance.
     * @param {Partial<Version>} [$$source = {}] - The source object to create the Version.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("FileID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["FileID"] = "";
        }
        if (!("VersionNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["VersionNumber"] = 0;
        }
        if (!("Path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("Author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Author"] = "";
        }
        if (!("Message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Message"] = "";
        }
        if (!("Content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Content"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Version instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Version}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Version(/** @type {Partial<Version>} */($$parsedSource));
    }
}
