// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as versioning$0 from "../../internal/versioning/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as diffmatchpatch$0 from "../../../../sergi/go-diff/diffmatchpatch/models.js";

/**
 * @param {string} name
 * @param {string} path
 * @returns {$CancellablePromise<versioning$0.File | null>}
 */
export function CreateFile(name, path) {
    return $Call.ByID(3418645411, name, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} versionID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteVersion(versionID) {
    return $Call.ByID(1352087182, versionID);
}

/**
 * @param {string} versionID
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function ExportVersion(versionID, filePath) {
    return $Call.ByID(2651241909, versionID, filePath);
}

/**
 * @param {string} v1
 * @param {string} v2
 * @returns {$CancellablePromise<diffmatchpatch$0.Diff[]>}
 */
export function GenerateDiff(v1, v2) {
    return $Call.ByID(433305361, v1, v2).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<versioning$0.File | null>}
 */
export function GetFile(id) {
    return $Call.ByID(1167542945, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} fileID
 * @returns {$CancellablePromise<versioning$0.Version | null>}
 */
export function GetVersion(fileID) {
    return $Call.ByID(1049863377, fileID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<(versioning$0.File | null)[]>}
 */
export function ListFiles() {
    return $Call.ByID(3557170708).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} fileID
 * @returns {$CancellablePromise<(versioning$0.Version | null)[]>}
 */
export function ListVersions(fileID) {
    return $Call.ByID(3148884800, fileID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} fileID
 * @param {string} versionID
 * @returns {$CancellablePromise<versioning$0.Version | null>}
 */
export function RestoreVersion(fileID, versionID) {
    return $Call.ByID(1999196387, fileID, versionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} fileID
 * @param {string} path
 * @param {string} author
 * @param {string} message
 * @param {string} content
 * @returns {$CancellablePromise<versioning$0.Version | null>}
 */
export function SaveVersion(fileID, path, author, message, content) {
    return $Call.ByID(2385940284, fileID, path, author, message, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = versioning$0.File.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = diffmatchpatch$0.Diff.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = versioning$0.Version.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType1);
const $$createType7 = $Create.Array($$createType5);
