// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Diff represents one diff operation
 */
export class Diff {
    /**
     * Creates a new Diff instance.
     * @param {Partial<Diff>} [$$source = {}] - The source object to create the Diff.
     */
    constructor($$source = {}) {
        if (!("Type" in $$source)) {
            /**
             * @member
             * @type {Operation}
             */
            this["Type"] = Operation.$zero;
        }
        if (!("Text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Diff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Diff}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Diff(/** @type {Partial<Diff>} */($$parsedSource));
    }
}

/**
 * Operation defines the operation of a diff item.
 * @readonly
 * @enum {number}
 */
export const Operation = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * DiffDelete item represents a delete diff.
     */
    DiffDelete: -1,

    /**
     * DiffInsert item represents an insert diff.
     */
    DiffInsert: 1,

    /**
     * DiffEqual item represents an equal diff.
     */
    DiffEqual: 0,
};
